# Generated by Django 2.1.15 on 2020-04-27 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Titre')),
                ('members', models.ManyToManyField(related_name='Membres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
