# Generated by Django 2.1.15 on 2020-04-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_comment_status_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='how',
        ),
    ]
