# Generated by Django 2.1.15 on 2020-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_task_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='Commentaires', to='taskmanager.Comment'),
        ),
    ]
