# Generated by Django 2.1.15 on 2020-05-08 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0015_auto_20200501_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('objet_project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Project', verbose_name='Projet')),
                ('objet_tache', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task', verbose_name='Tache')),
            ],
        ),
        migrations.CreateModel(
            name='Verbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100, verbose_name='Verbe')),
            ],
        ),
        migrations.AddField(
            model_name='trace',
            name='verbe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Verbe', verbose_name='Verbe'),
        ),
    ]
