# Generated by Django 2.1.15 on 2020-05-08 09:03

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('taskmanager', '0016_auto_20200508_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verbe',
            new_name='Verb',
        ),
    ]
