# Generated by Django 2.1.15 on 2020-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0018_auto_20200508_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='alias',
            field=models.CharField(default='VB', max_length=10, verbose_name='Alias'),
        ),
    ]
