# Generated by Django 2.1.15 on 2020-05-08 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0019_verb_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
            preserve_default=False,
        ),
    ]
