# Generated by Django 2.1.15 on 2020-05-08 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0020_trace_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trace',
            old_name='object_tache',
            new_name='object_task',
        ),
        migrations.AlterField(
            model_name='trace',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
