# Generated by Django 2.1.15 on 2020-05-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0024_auto_20200510_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='extension_integer',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Extension numérique'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.IntegerField(default=0, verbose_name='Avancement'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.IntegerField(default=0, verbose_name='Avancement'),
        ),
    ]
