# Generated by Django 2.1.15 on 2020-05-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0025_auto_20200511_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='alias',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Alias'),
        ),
    ]
